a=int(input("Enter score by player 1: "))
b=int(input("Enter score by player 2: "))
c=int(input("Enter score by player 3: "))
print("Strike rate of player 1: ",a*100/60)
print("Strike rate of player 2: ",b*100/60)
print("Strike rate of player 3: ",c*100/60)
print("Score of player 1 if 60 more balls are given : ",a*2)
print("Score of player 2 if 60 more balls are given : ",b*2)
print("Score of player 3 if 60 more balls are given: ",c*2)
print("Maximum number of sixes player 1 could hit: ",a//6)
print("Maximum number of sixes player 2 could hit: ",b//6)
print("Maximum number of sixes player 3 could hit: ",c//6)
